[package]
name = "zen_sm"
version = "0.1.0"
authors = ["Rafael Rondao <rafael.rondao@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = "0.12.0"
serde = { version = "1", features = ["derive"], optional = true }
zen = { version = "0.1.0", path = "../zen" }

[features]
default = ["eframe/http"]
http = ["eframe/http"]
persistence = ["eframe/persistence", "serde"]

[profile.release]
opt-level = 2 # fast and small wasm
